collection:
  size: 10000
  start_index: 0
  license_url: https://...
  license_hash:

wallet:
  receive_address: xch...
  royalties_address: xch...
  did: did:chia:...
  nft_wallet_id: 4
  price_xch: 1000000000000
  royalties_percent: 500
  minting_fees: 100000

path:
  images: assets/images/
  metadata: assets/metadata/

key:
  nft_storage_api:

db:
  database:
  host: localhost
  port: 5432
  user:
  password: