meta:
  collection_name: The collection name
  collection_description: A short description of the collection
  website: https://...
  banner_url: https://...
  icon_url: https://...
  twitter: @...

wallet:
  receive_address: xch...
  royalties_address: xch...
  did: did:chia:...
  nft_wallet_id:
  price_xch: 1000000000000
  royalties_percent: 5000
  minting_fees: 100000

path:
  images: assets/images/
  metadata: assets/metadata/

key:
  nft_storage_api:

db:
  db_name:
  host: localhost
  port: 5432
  user:
  password: